name: Setup Summon
description: 'Setup Summon for use in your GitHub Actions workflow'
inputs:
  version:
    description: 'The version of Summon to install'
    required: true
    default: 'v0.10.4'
  download-url:
    description: 'The URL to download Summon from'
    required: true
    default: 'https://github.com/cyberark/summon/releases/download'
runs:
  using: "composite"
  steps:
    - name: Check if Summon is already installed on Linux
      if: runner.os == 'Linux'
      id: check-summon-linux
      shell: bash
      run: |
        # check-summon
        if command -v summon &> /dev/null; then
          INSTALLED_VERSION="$(summon --version | sed -e 's/^summon version //')"
          if printf -- '%s' "v${INSTALLED_VERSION}" | egrep -q -- "${SUMMON_VERSION}"
          then
            echo "install-summon=false" >> "$GITHUB_OUTPUT"
            echo "::debug::Summon is installed at version ${INSTALLED_VERSION}"
          else
            echo "install-summon=true" >> "$GITHUB_OUTPUT"
            echo "::debug::Summon version does not match. Installed: ${INSTALLED_VERSION}, Required: ${SUMMON_VERSION}"
          fi
        else
          echo "install-summon=true" >> "$GITHUB_OUTPUT"
          echo "::debug::Summon is not installed"
        fi
      env:
        SUMMON_VERSION: ${{ inputs.version }}

    - name: Gather info for linux
      if: runner.os == 'Linux' && steps.check-summon-linux.outputs.install-summon == 'true'
      id: info-linux
      shell: bash
      run: |
        # info-linux
        PROC_TYPE="$(uname -p)"
        if [[ "${PROC_TYPE}" == "x86_64" ]]; then
          echo "asset-name=summon-linux-amd64" >> "$GITHUB_OUTPUT"
        elif [[ "${PROC_TYPE}" == "aarch64" ]]; then
          echo "asset-name=summon-linux-arm64" >> "$GITHUB_OUTPUT"
        else
          echo "error: unsupported architecture: ${PROC_TYPE}"
          exit 1
        fi

        TARGET_DIR=$(mktemp -d -t summon.XXXXXX)
        echo "destination-folder=${TARGET_DIR}" >> "$GITHUB_OUTPUT"


    - name: Setup on Linux
      if: runner.os == 'Linux' && steps.check-summon-linux.outputs.install-summon == 'true'
      id: setup-linux
      shell: bash
      run: |
        # setup-linux
        curl -LsJ "${DOWNLOAD_URL}/${VERSION}/${ASSET_NAME}.tar.gz" -o "${DESTINATION_FOLDER}/${ASSET_NAME}.tar.gz"
        tar -xzf "${DESTINATION_FOLDER}/${ASSET_NAME}.tar.gz" -C "${DESTINATION_FOLDER}"
        chmod +x "${DESTINATION_FOLDER}/summon"
        echo "${DESTINATION_FOLDER}" >> $GITHUB_PATH
      env:
        VERSION: ${{ inputs.version }}
        DOWNLOAD_URL: ${{ inputs.download-url }}
        ASSET_NAME: ${{ steps.info-linux.outputs.asset-name }}
        DESTINATION_FOLDER: ${{ steps.info-linux.outputs.destination-folder }}
